ProyectoIngenieria/ProyectoIngenieria/Controllers/VoluntariesController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.IO;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using PagedList;
using ProyectoIngenieria.DB;
namespace ProyectoIngenieria.Controllers
{
    public class VoluntariesController : Controller
    {
        private ProyectoIngenieriaEntities db = new ProyectoIngenieriaEntities();

        // GET: Voluntaries
        public ActionResult Index(string mensaje, int page = 1, int pageSize = 6)
        {
            List<Voluntary> volutaryList = db.Voluntary.ToList();
            PagedList<Voluntary> model = new PagedList<Voluntary>(volutaryList, page, pageSize);

            //Mensaje de exito para eliminar o editar
            if (mensaje != null)
            {
                ViewBag.menssage = mensaje;
            }

            return View(model);
        }

        // GET: Voluntaries/Details/5
        public ActionResult Details(string id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Voluntary voluntary = db.Voluntary.Find(id);
            if (voluntary == null)
            {
                return HttpNotFound();
            }
            ViewBag.image = Path.Combine("/Static/", voluntary.Photo.image);
            ViewBag.name = voluntary.name + " " + voluntary.last_name;

            return View(voluntary);
        }

        // GET: Voluntaries/Create
        public ActionResult Create(string mensaje)
        {
            ViewBag.photo_id = new SelectList(db.Photo, "id", "name");

            //Mensaje de id repetido
            if (mensaje != null)
            {
                ViewBag.menssage = mensaje;
            }

            return View();
        }

        // POST: Voluntaries/Create
        // Para protegerse de ataques de publicación excesiva, habilite las propiedades específicas a las que desea enlazarse. Para obtener 
        // más información vea https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "identification,name,last_name,state,photo_id,email,address,phone_number,link,description")] Voluntary voluntary, Boolean state, HttpPostedFileBase File, string nameFile, string description)
        {
            var query = (from r in db.Voluntary where r.identification == voluntary.identification select r).Count();
            if (query == 1)
            {
                return RedirectToAction("Create/"+voluntary.identification, new { mensaje = "El voluntario con la identificación " + voluntary.identification + " ya se encuentra registrado en el sistema" });
            }
            else
            {
                if (ModelState.IsValid)
                {
                    voluntary.state = state;

                    if (File == null)
                    {
                        ViewBag.MessagePhoto = "Debe ingresar una imagen";
                        return View();
                    }
                    else
                    {

                        if (nameFile == "")
                        {
                            ViewBag.MessagePhotoName = "Debe ingresar un nombre";
                            ViewBag.MessagePhoto = "Debe ingresar una imagen";
                            return View();
                        }
                        else
                        {
                            var extension = Path.GetExtension(File.FileName);
                            var path = Path.Combine(Server.MapPath("/Static/"), nameFile + extension);

                            var Photo = new DB.Photo();
                            Photo.name = nameFile;
                            Photo.image = nameFile + extension;
                            File.SaveAs(path);

                            db.Photo.Add(Photo);

                            voluntary.description = description;
                            db.Voluntary.Add(voluntary);
                            db.SaveChanges();
                        }
                    }

                    return RedirectToAction("Index", new { mensaje = "El voluntario " + voluntary.name + " " + voluntary.last_name + " ha sido ingresado exitosamente" });
                }
            }

            return View(voluntary);
        }

        // GET: Voluntaries/Edit/5
        public ActionResult Edit(string id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Voluntary voluntary = db.Voluntary.Find(id);
            if (voluntary == null)
            {
                return HttpNotFound();
            }
            ViewBag.image = Path.Combine("/Static/", voluntary.Photo.image);
            ViewBag.name = voluntary.Photo.name;

            ViewBag.description = voluntary.description;
            return View(voluntary);
        }

        // POST: Voluntaries/Edit/5
        // Para protegerse de ataques de publicación excesiva, habilite las propiedades específicas a las que desea enlazarse. Para obtener 
        // más información vea https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "identification,name,last_name,description,state,photo_id,email,address,phone_number,link")] Voluntary voluntary, Boolean state, HttpPostedFileBase File, string nameFile, string description)
        {
            if (ModelState.IsValid)
            {
                db.Entry(voluntary).State = EntityState.Modified;
                voluntary.state = state;

                if (File != null)
                {
                    if (nameFile != "")
                    {
                        var Photo = db.Photo.Find(voluntary.photo_id);
                        Photo.name = nameFile;

                        //elimina la imagen anterior
                        var locationStatic = Path.Combine(Server.MapPath("/Static/"));
                        System.IO.File.Delete(locationStatic + Photo.image);

                        var extension = Path.GetExtension(File.FileName);
                        var path = Path.Combine(Server.MapPath("/Static/"), nameFile + extension);
                        File.SaveAs(path);
                        Photo.image = nameFile + extension;

                        db.SaveChanges();
                    }
                }
                if (nameFile != "")
                {
                    var Photo = db.Photo.Find(voluntary.photo_id);
                    Photo.name = nameFile;

                    db.SaveChanges();
                }

                voluntary.description = description;
                db.SaveChanges();

                return RedirectToAction("Index", new { mensaje = "El voluntario " + voluntary.name + " " + voluntary.last_name + " ha sido actualizado exitosamente" });
            }
            return View(voluntary);
        }

        // GET: Voluntaries/Delete/5
        public ActionResult Delete(string id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }

            Voluntary voluntary = db.Voluntary.Find(id);

            if (voluntary == null)
            {
                return HttpNotFound();
            }

            ViewBag.image = Path.Combine("/Static/", voluntary.Photo.image);
            ViewBag.name = voluntary.name + " " + voluntary.last_name;

            return View(voluntary);
        }

        // POST: Voluntaries/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(string id)
        {

            Voluntary voluntary = db.Voluntary.Find(id);
            Photo Photo = db.Photo.Find(voluntary.photo_id);

            //Valida si ya existe un voluntario asociado a una actividad

            if (voluntary.Activity.Count() >0)
            {
                List<Activity> activities = voluntary.Activity.ToList();

                for (int i=0; i > activities.Count(); i++)
                {
                 
                    voluntary.Activity.Remove(activities[i]);
                }
            }

            //eliminar imagen
            var locationStatic = Path.Combine(Server.MapPath("/Static/"));
            System.IO.File.Delete(locationStatic + Photo.image);

            db.Photo.Remove(Photo);
            db.Voluntary.Remove(voluntary);

            db.SaveChanges();
            return RedirectToAction("Index", new { mensaje = "El voluntario " + voluntary.name + " " + voluntary.last_name + " ha sido eliminado exitosamente" });

        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

ProyectoIngenieria/ProyectoIngenieria/Views/Voluntaries/Create.cshtml
@model ProyectoIngenieria.DB.Voluntary


@Html.Partial("~/Views/Home/AdminMenu.cshtml")
@using (Html.BeginForm("Create", "Voluntaries", FormMethod.Post, new { enctype = "multipart/form-data" }))
{
    @Html.AntiForgeryToken()

    <div class="container md-3">
        <br />
        <h1 class="text-center">Ingresar un Voluntario</h1>
        <br />
        <br />
        @if (ViewBag.menssage != null)
        {
            <div class="alert alert-danger text-center alert-dismissible">
                <h3 class="alert-heading"><i class="icon fa fa-check"></i> ¡Error!</h3>
                <button type="button" class="close" data-dismiss="alert" aria-hidden="true">x</button>
                <h6>@ViewBag.menssage</h6>
            </div>
        }
        <div class="panel-body">
            <div class="row">
                <div class="col-md-1"></div>
                <div class="col-md-5">
                    @Html.ValidationSummary(true, "", new { @class = "text-danger" })
                    <div class="form-group">
                        @Html.LabelFor(model => model.identification, htmlAttributes: new { @class = "control-label col-md-2" })
                        <div class="col-md-10">
                            @Html.EditorFor(model => model.identification, new { htmlAttributes = new { @class = "form-control" } })
                            @Html.ValidationMessageFor(model => model.identification, "", new { @class = "text-danger" })
                        </div>
                    </div>

                    <div class="form-group">
                        @Html.LabelFor(model => model.name, htmlAttributes: new { @class = "control-label col-md-2" })
                        <div class="col-md-10">
                            @Html.EditorFor(model => model.name, new { htmlAttributes = new { @class = "form-control" } })
                            @Html.ValidationMessageFor(model => model.name, "", new { @class = "text-danger" })
                        </div>
                    </div>

                    <div class="form-group">
                        @Html.LabelFor(model => model.last_name, htmlAttributes: new { @class = "control-label col-md-2" })
                        <div class="col-md-10">
                            @Html.EditorFor(model => model.last_name, new { htmlAttributes = new { @class = "form-control" } })
                            @Html.ValidationMessageFor(model => model.last_name, "", new { @class = "text-danger" })
                        </div>
                    </div>

                    <div class="form-group">
                        @Html.LabelFor(model => model.address, htmlAttributes: new { @class = "control-label col-md-2" })
                        <div class="col-md-10">
                            @Html.EditorFor(model => model.address, new { htmlAttributes = new { @class = "form-control" } })
                            @Html.ValidationMessageFor(model => model.address, "", new { @class = "text-danger" })
                        </div>
                    </div>

                    <div class="form-group">
                        @Html.LabelFor(model => model.state, htmlAttributes: new { @class = "control-label col-md-2" })
                        <div class="col-md-10">
                            <select ; id="state" name="state" class="form-control">
                                <option value="true">Activo</option>
                                <option value="false">No activo</option>
                            </select>
                            @Html.ValidationMessageFor(model => model.state, "", new { @class = "text-danger" })
                        </div>
                    </div>

                    <div class="form-group">
                        @Html.LabelFor(model => model.email, htmlAttributes: new { @class = "control-label col-md-2" })
                        <div class="col-md-10">
                            @Html.EditorFor(model => model.email, new { htmlAttributes = new { @class = "form-control" } })
                            @Html.ValidationMessageFor(model => model.email, "", new { @class = "text-danger" })
                        </div>
                    </div>
                </div>

                <div class="col-md-5">

                    <div class="form-group">
                        @Html.LabelFor(model => model.phone_number, htmlAttributes: new { @class = "control-label col-md-6" })
                        <div class="col-md-10">
                            @Html.EditorFor(model => model.phone_number, new { htmlAttributes = new { @class = "form-control" } })
                            @Html.ValidationMessageFor(model => model.phone_number, "", new { @class = "text-danger" })
                        </div>
                    </div>

                    <div class="form-group">
                        @Html.LabelFor(model => model.description, htmlAttributes: new { @class = "control-label col-md-2" })
                        <div class="col-md-10">
                            <textarea id="description" name="description" class="form-control" rows="6" cols="63" style="resize:none;"></textarea>

                            @Html.ValidationMessageFor(model => model.description, "", new { @class = "text-danger" })
                        </div>
                    </div>
                    <div class="form-group">

                        <div class="col-md-10 ">
                            Seleccione una foto
                            <br />

                            <input type="file" name="File" id="File" />
                        </div>
                        @if (ViewBag.MessagePhoto != null)
                        {
                            <div class="col-md-10">
                                <div class="alert alert-danger">
                                    @ViewBag.MessagePhoto
                                </div>
                            </div>
                        }
                    </div>

                    <div class="form-group">

                        <div class="col-md-10">
                            Nombre de la imagen
                            <br />

                            <input type="text" name="nameFile" id="nameFile" class="form-control" />

                        </div>
                        @if (ViewBag.MessagePhotoName != null)
                        {
                            <div class="col-md-5">
                                <div class="alert alert-danger">
                                    @ViewBag.MessagePhotoName
                                </div>
                            </div>
                        }
                    </div>

                    <div class="form-group">
                        @Html.LabelFor(model => model.link, htmlAttributes: new { @class = "control-label col-md-6" })
                        <div class="col-md-10">
                            @Html.EditorFor(model => model.link, new { htmlAttributes = new { @class = "form-control" } })
                            @Html.ValidationMessageFor(model => model.link, "", new { @class = "text-danger" })
                        </div>
                    </div>
                </div>
            </div>
            <br />
            <div class="row">
                <div class="col-md-4">
                </div>
                <div class="form-group">
                    <div class="col-md-2">
                        <a href="/Voluntaries/Index" class="btn btn-primary btn-md text-uppercase">Cancelar</a>
                    </div>
                </div>
                <div class="form-group">
                    <div class="col-md-2">
                        <input type="submit" value="Guardar" class="btn btn-primary btn-md text-uppercase" />
                    </div>
                </div>

            </div>
            <br />
        </div>
    </div>
}
<hr />

<style>

    #mainNav {
        background-color: rgb(46,49,146);
    }

    .md-3 {
        box-shadow: 5px 0px 40px rgba(0,0,0, .2);
        width: 97%;
        margin-top: 8%;
    }

    .panel {
        border-radius: 0 !important;
        transition: box-shadow 0.5s;
        width: 55%;
    }

    .form-group {
        align-content: center;
    }
</style>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

ProyectoIngenieria/ProyectoIngenieria/Views/Voluntaries/Delete.cshtml
@model ProyectoIngenieria.DB.Voluntary

@{
    ViewBag.Title = "Delete";
}

@Html.Partial("~/Views/Home/AdminMenu.cshtml")

    <div class="container md-3">
        <br />
        <h3 class="text-center">¿Está seguro que desea el eliminar a este voluntario del sistema?</h3>
        <br />
        <br />
        <div class="panel-body ">
            <div class="row">

                <div class="col-sm-6 ">

                    <dl class="dl-horizontal margen">

                        <dt>
                            <p class="text-muted">@Html.DisplayNameFor(model => model.name)</p>
                        </dt>

                        <dd>
                            <p>@(ViewBag.name)</p>
                        </dd>

                        <dt>
                            <p class="text-muted">@Html.DisplayNameFor(model => model.description)</p>
                        </dt>

                        <dd>
                            @Html.DisplayFor(model => model.description)
                        </dd>

                        <dt>
                            <p class="text-muted">@Html.DisplayNameFor(model => model.email)</p>
                        </dt>

                        <dd>
                            @Html.DisplayFor(model => model.email)
                        </dd>

                        <dt>
                            <p class="text-muted">@Html.DisplayNameFor(model => model.address)</p>

                        </dt>

                        <dd>
                            @Html.DisplayFor(model => model.address)
                        </dd>

                        <dt>
                            <p class="text-muted">@Html.DisplayNameFor(model => model.phone_number)</p>

                        </dt>

                        <dd>
                            @Html.DisplayFor(model => model.phone_number)
                        </dd>

                        <dt>
                            <p class="text-muted">@Html.DisplayNameFor(model => model.state)</p>

                        </dt>

                        <dd>
                            @Html.DisplayFor(model => model.state)
                        </dd>

                    </dl>
                </div>
                <div class="col-sm-6">
                    <img src="@(ViewBag.image)" width="65%;" height="65%;" class="img rounded-circle" />
                </div>
            </div>
        </div>
        <br />

        <div class="row" style="margin-top:2%;">
            <div class="col-md-4">
            </div>
            <div class="form-group">
                <div class="col-md-2">
                    <a href="/Voluntaries/Index" class="btn btn-primary btn-md text-uppercase">Cancelar</a>
                </div>
            </div>
            <div class="form-group">
                <div class="col-md-2">
                    @using (Html.BeginForm())
                    {
                        @Html.AntiForgeryToken()

                        <input type="submit" value="Eliminar" class="btn btn-primary btn-md text-uppercase" />
                    }
                </div>
            </div>
        </div>

        <br />
        <br />
    </div>
<hr />

<style>
    .img {
        margin-top: -1%;
        margin-left: 15%;
    }

    .margen {
        margin-left: 22%;
    }

    #mainNav {
        background-color: rgb(46,49,146);
    }

    .md-3 {
        box-shadow: 5px 0px 40px rgba(0,0,0, .2);
        width: 60%;
        margin-top: 8%;
    }

    .panel {
        border-radius: 0 !important;
        transition: box-shadow 0.5s;
        width: 55%;
    }
</style>

ProyectoIngenieria/ProyectoIngenieria/Views/Voluntaries/Edit.cshtml
@model ProyectoIngenieria.DB.Voluntary

@{
    ViewBag.Title = "Edit";
}

@Html.Partial("~/Views/Home/AdminMenu.cshtml")

@using (Html.BeginForm("Edit", "Voluntaries", FormMethod.Post, new { enctype = "multipart/form-data" }))
{
    @Html.AntiForgeryToken()

    <div class="container md-3">
        <br />
        <h1 class="text-center">Editar un voluntario</h1>
        <br />
        <br />
        <div class="panel-body">
            <div class="row">
                <div class="col-md-1"></div>
                <div class="col-md-5">
                    @Html.ValidationSummary(true, "", new { @class = "text-danger" })
                    @Html.HiddenFor(model => model.identification)

                    <div class="form-group">
                        @Html.LabelFor(model => model.name, htmlAttributes: new { @class = "control-label col-md-2" })
                        <div class="col-md-10">
                            @Html.EditorFor(model => model.name, new { htmlAttributes = new { @class = "form-control" } })
                            @Html.ValidationMessageFor(model => model.name, "", new { @class = "text-danger" })
                        </div>
                    </div>

                    <div class="form-group">
                        @Html.LabelFor(model => model.last_name, htmlAttributes: new { @class = "control-label col-md-2" })
                        <div class="col-md-10">
                            @Html.EditorFor(model => model.last_name, new { htmlAttributes = new { @class = "form-control" } })
                            @Html.ValidationMessageFor(model => model.last_name, "", new { @class = "text-danger" })
                        </div>
                    </div>

                    <div class="form-group">
                        @Html.LabelFor(model => model.state, htmlAttributes: new { @class = "control-label col-md-2" })
                        <div class="col-md-10">
                            <select style="width:100%" ; id="state" name="state" class="form-control">
                                @if (Model.state == false)
                                {
                                    <option value="true">Activo</option>
                                    <option value="false" selected>No activo</option>
                                }
                                else
                                {
                                    <option value="true" selected>Activo</option>
                                    <option value="false">No activo</option>
                                }
                            </select>
                            @Html.ValidationMessageFor(model => model.state, "", new { @class = "text-danger" })

                        </div>
                    </div>

                    <div class="form-group">
                        @Html.LabelFor(model => model.address, htmlAttributes: new { @class = "control-label col-md-2" })
                        <div class="col-md-10">
                            @Html.EditorFor(model => model.address, new { htmlAttributes = new { @class = "form-control" } })
                            @Html.ValidationMessageFor(model => model.address, "", new { @class = "text-danger" })
                        </div>
                    </div>

                    <div class="form-group">
                        @Html.LabelFor(model => model.email, htmlAttributes: new { @class = "control-label col-md-2" })
                        <div class="col-md-10">
                            @Html.EditorFor(model => model.email, new { htmlAttributes = new { @class = "form-control" } })
                            @Html.ValidationMessageFor(model => model.email, "", new { @class = "text-danger" })
                        </div>
                    </div>

                    <div class="form-group">
                        @Html.LabelFor(model => model.phone_number, htmlAttributes: new { @class = "control-label col-md-6" })
                        <div class="col-md-10">
                            @Html.EditorFor(model => model.phone_number, new { htmlAttributes = new { @class = "form-control" } })
                            @Html.ValidationMessageFor(model => model.phone_number, "", new { @class = "text-danger" })
                        </div>
                    </div>

                  
                </div>
                <div class="col-md-5">


                    <div class="form-group">
                        <a>Foto Actual</a>
                        <div class="col-md-10">

                            <img src="@(ViewBag.image)" width="60%;" height="100%;" />
                        </div>
                    </div>

                    <div class="form-group">
                        @Html.HiddenFor(model => model.photo_id)
                    </div>

                    <div class="form-group">
                        @Html.LabelFor(model => model.description, htmlAttributes: new { @class = "control-label col-md-2" })
                        <div class="col-md-10">
                            <textarea id="description" name="description" class="form-control" rows="6" cols="63" style="resize:none;">@(ViewBag.description)</textarea>
                            @Html.ValidationMessageFor(model => model.description, "", new { @class = "text-danger" })
                        </div>
                    </div>

                    <div class="form-group">

                        <div class="col-md-10">
                            Seleccione una foto
                            <br />
                            <input type="file" name="File" id="File" class="form-group" />
                        </div>
                    </div>

                    <div class="form-group">

                        <div class="col-md-10 ">
                            Nombre de la imagen
                            <br />
                            <input type="text" name="nameFile" id="nameFile" value="@(ViewBag.name)" class="form-control" />

                        </div>
                    </div>

                    <div class="form-group">
                        @Html.LabelFor(model => model.link, htmlAttributes: new { @class = "control-label col-md-6" })
                        <div class="col-md-10">
                            @Html.EditorFor(model => model.link, new { htmlAttributes = new { @class = "form-control" } })
                            @Html.ValidationMessageFor(model => model.link, "", new { @class = "text-danger" })
                        </div>
                    </div>
                </div>
            </div>
            <br />
            <div class="row">
                <div class="col-md-4">
                </div>
                <div class="form-group">
                    <div class="col-md-2">
                        <a href="/Voluntaries/Index" class="btn btn-primary btn-md text-uppercase">Cancelar</a>
                    </div>
                </div>
                <div class="form-group">
                    <div class="col-md-2">
                        <input type="submit" value="Guardar" class="btn btn-primary btn-md text-uppercase" />
                    </div>
                </div>

            </div>
            <br />
        </div>
    </div>
}
<hr />

<style>

    #mainNav {
        background-color: rgb(46,49,146);
    }

    .md-3 {
        box-shadow: 5px 0px 40px rgba(0,0,0, .2);
        width: 97%;
        margin-top: 10%;
    }

    .panel {
        border-radius: 0 !important;
        transition: box-shadow 0.5s;
        width: 55%;
    }

    .form-group {
        align-content: center;
    }
</style>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}