ProyectoIngenieria/ProyectoIngenieria/Controllers/SponsorsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.IO;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using PagedList;
using ProyectoIngenieria.DB;

namespace ProyectoIngenieria.Controllers
{
    public class SponsorsController : Controller
    {
        private ProyectoIngenieriaEntities db = new ProyectoIngenieriaEntities();

        // GET: Sponsors
        public ActionResult Index(string message, int page = 1, int pageSize = 4)
        {

            if (message != null)
            {
                ViewBag.message = message;
            }
            List<Sponsor> sponsorList = db.Sponsor.ToList();
            PagedList<Sponsor> model = new PagedList<Sponsor>(sponsorList, page, pageSize);
            return View(model);
        }

        // GET: Sponsors/Details/5
        public ActionResult Details(string id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Sponsor sponsor = db.Sponsor.Find(id);
            if (sponsor == null)
            {
                return HttpNotFound();
            }

            ViewBag.image = Path.Combine("/Static/", sponsor.Photo.image);
            return View(sponsor);
        }

        // GET: Sponsors/Create
        public ActionResult Create(string message)
        {
            if (message != null)
            {
                ViewBag.message = message;
            }
            return View();
        }

        // GET: Sponsors/CreateEnterprise
        public ActionResult CreateSponsorEnterprise(string message)
        {
            if (message != null)
            {
                ViewBag.message = message;
            }
            return View();
        }

        // POST: Sponsors/Create
        // Para protegerse de ataques de publicación excesiva, habilite las propiedades específicas a las que desea enlazarse. Para obtener 
        // más información vea https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "identification,name,last_name,email,phone_number,description,photo_id")] Sponsor sponsor, HttpPostedFileBase File, string nameFile)
        {
            if (ModelState.IsValid)
            {
                var query = (from r in db.Sponsor where r.identification == sponsor.identification select r).Count();
                if (query == 1)
                {
                    return RedirectToAction("Create", new { message = "El patrocinador con la identificación " + sponsor.identification + " ya se encuentra registrado" });
                }
                else
                {
                    if (File == null)
                    {
                        ViewBag.message = "Debe ingresar una imagen";
                        return View(sponsor);
                    }
                    else
                    {
                        if (nameFile == "")
                        {
                            ViewBag.message = "Debe ingresar un nombre para la imagen";
                            return View(sponsor);
                        }
                        else
                        {
                            var extension = Path.GetExtension(File.FileName);
                            var path = Path.Combine(Server.MapPath("/Static/"), nameFile + extension);

                            var Photo = new DB.Photo();
                            Photo.name = nameFile;
                            Photo.image = nameFile + extension;
                            File.SaveAs(path);

                            db.Photo.Add(Photo);
                            db.SaveChanges();

                            sponsor.photo_id = Photo.id;

                            db.Sponsor.Add(sponsor);
                            db.SaveChanges();
                        }
                    }

                    return RedirectToAction("Index", new { message = "El patrocinador ha sido registrado exitosamente" });
                }
            }
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult CreateSponsorEnterprise([Bind(Include = "identification,name,last_name,email,phone_number,description")] Sponsor sponsor, HttpPostedFileBase File, string nameFile)
        {
            if (ModelState.IsValid)
            {
                var query = (from r in db.Sponsor where r.identification == sponsor.identification select r).Count();
                if (query == 1)
                {
                    return RedirectToAction("CreateSponsorEnterprise", new { message = "El patrocinador con la identificación " + sponsor.identification + " ya se encuentra registrado" });

                }
                else
                {
                    if (File == null)
                    {
                        ViewBag.message = "Debe ingresar una imagen";
                        return View(sponsor);
                    }
                    else
                    {
                        if (nameFile == "")
                        {
                            ViewBag.message = "Debe ingresar un nombre para la imagen";
                            return View(sponsor);
                        }
                        else
                        {
                            var extension = Path.GetExtension(File.FileName);
                            var path = Path.Combine(Server.MapPath("/Static/"), nameFile + extension);

                            var Photo = new DB.Photo();
                            Photo.name = nameFile;
                            Photo.image = nameFile + extension;
                            File.SaveAs(path);

                            db.Photo.Add(Photo);
                            db.SaveChanges();

                            sponsor.photo_id = Photo.id;

                            db.Sponsor.Add(sponsor);
                            db.SaveChanges();
                        }
                    }

                    return RedirectToAction("Index", new { message = "El patrocinador ha sido registrado exitosamente" });

                }
            }
            return View();
        }


        // GET: Sponsors/Edit/5
        public ActionResult Edit(string id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Sponsor sponsor = db.Sponsor.Find(id);
            if (sponsor == null)
            {
                return HttpNotFound();
            }

            if (sponsor.last_name == "Empresa")
            {
                ViewBag.enterprise = "Empresa";
            }
            ViewBag.name = sponsor.Photo.name;
            ViewBag.image = Path.Combine("/Static/", sponsor.Photo.image);
            return View(sponsor);
        }

        // POST: Sponsors/Edit/5

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "identification,name,last_name,email,phone_number,description,photo_id")] Sponsor sponsor, HttpPostedFileBase File, string nameFile)
        {

            if (ModelState.IsValid)
            {
                db.Entry(sponsor).State = EntityState.Modified;

                if (File != null)
                {
                    if (nameFile != "")
                    {
                        var Photo = db.Photo.Find(sponsor.photo_id);
                        Photo.name = nameFile;

                        //elimina la imagen anterior
                        var locationStatic = Path.Combine(Server.MapPath("/Static/"));
                        System.IO.File.Delete(locationStatic + Photo.image);

                        var extension = Path.GetExtension(File.FileName);
                        var path = Path.Combine(Server.MapPath("/Static/"), nameFile + extension);
                        File.SaveAs(path);
                        Photo.image = nameFile + extension;

                        db.SaveChanges();
                    }
                }

                if (nameFile != "")
                {
                    var Photo = db.Photo.Find(sponsor.photo_id);
                    Photo.name = nameFile;

                    db.SaveChanges();
                }

                db.SaveChanges();
                return RedirectToAction("Index", new { message = "El patrocinador ha sido actualizado exitosamente" });

            }

            return View(sponsor);

        }

        // GET: Sponsors/Delete/5
        public ActionResult Delete(string id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Sponsor sponsor = db.Sponsor.Find(id);
            if (sponsor == null)
            {
                return HttpNotFound();
            }
            ViewBag.image = Path.Combine("/Static/", sponsor.Photo.image);
            return View(sponsor);
        }

        // POST: Sponsors/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(string id)
        {
            Sponsor sponsor = db.Sponsor.Find(id);

            Photo Photo = db.Photo.Find(sponsor.photo_id);

            //eliminar imagen
            var locationStatic = Path.Combine(Server.MapPath("/Static/"));
            System.IO.File.Delete(locationStatic + Photo.image);
            sponsor.Activity.Clear();
            db.Photo.Remove(Photo);
            db.Sponsor.Remove(sponsor);
            

            db.SaveChanges();
            return RedirectToAction("Index", new { message = "El patrocinador ha sido eliminado exitosamente" });

        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)

ProyectoIngenieria/ProyectoIngenieria/Views/Sponsors/Create.cshtml
@model ProyectoIngenieria.DB.Sponsor


@Html.Partial("~/Views/Home/AdminMenu.cshtml")
@using (Html.BeginForm("Create", "Sponsors", FormMethod.Post, new { enctype = "multipart/form-data" }))
{
    @Html.AntiForgeryToken()

    <div class="container md-3">
        <br />
        <h1 class="text-center">Ingresar un Patrocinador Persona</h1>
        <br />
        <br />
        @if (ViewBag.message != null)
        {
            <div class="alert alert-danger text-center alert-dismissible">
                <h4 class="alert-heading"><i class="icon fa fa-check"></i> ¡Error!</h4>
                <button type="button" class="close" data-dismiss="alert" aria-hidden="true">x</button>
                <h6>@ViewBag.message</h6>
            </div>
        }
        <div class="panel-body">
            <div class="row">
                <div class="col-md-1"></div>
                <div class="col-md-5">
                    @Html.ValidationSummary(true, "", new { @class = "text-danger" })
                    <div class="form-group">
                        @Html.LabelFor(model => model.identification, htmlAttributes: new { @class = "control-label col-md-5" })
                        <div class="col-md-10">
                            @Html.EditorFor(model => model.identification, new { htmlAttributes = new { @class = "form-control" } })
                            @Html.ValidationMessageFor(model => model.identification, "", new { @class = "text-danger" })
                        </div>
                    </div>

                    <div class="form-group">
                        @Html.LabelFor(model => model.name, htmlAttributes: new { @class = "control-label col-md-2" })
                        <div class="col-md-10">
                            @Html.EditorFor(model => model.name, new { htmlAttributes = new { @class = "form-control" } })
                            @Html.ValidationMessageFor(model => model.name, "", new { @class = "text-danger" })
                        </div>
                    </div>

                    <div class="form-group">
                        @Html.LabelFor(model => model.last_name, htmlAttributes: new { @class = "control-label col-md-2" })
                        <div class="col-md-10">
                            @Html.EditorFor(model => model.last_name, new { htmlAttributes = new { @class = "form-control" } })
                            @Html.ValidationMessageFor(model => model.last_name, "", new { @class = "text-danger" })
                        </div>
                    </div>

                    <div class="form-group">
                        @Html.LabelFor(model => model.email, htmlAttributes: new { @class = "control-label col-md-2" })
                        <div class="col-md-10">
                            @Html.EditorFor(model => model.email, new { htmlAttributes = new { @class = "form-control" } })
                            @Html.ValidationMessageFor(model => model.email, "", new { @class = "text-danger" })
                        </div>
                    </div>
                </div>
                <div class="col-md-5">
                    <div class="form-group">
                        @Html.LabelFor(model => model.phone_number, htmlAttributes: new { @class = "control-label col-md-2" })
                        <div class="col-md-10">
                            @Html.EditorFor(model => model.phone_number, new { htmlAttributes = new { @class = "form-control" } })
                            @Html.ValidationMessageFor(model => model.phone_number, "", new { @class = "text-danger" })
                        </div>
                    </div>

                    <div class="form-group">
                        @Html.LabelFor(model => model.description, htmlAttributes: new { @class = "control-label col-md-2" })
                        <div class="col-md-10">
                            @Html.EditorFor(model => model.description, new { htmlAttributes = new { @class = "form-control" } })
                            @Html.ValidationMessageFor(model => model.description, "", new { @class = "text-danger" })
                        </div>
                    </div>
                    <div class="form-group">

                        <div class="col-md-10">
                            Seleccione una foto
                            <br />
                            <input type="file" name="File" id="File" />
                        </div>
                    </div>
                    <br />
                    <div class="form-group">

                        <div class="col-md-10">
                            Nombre de la imagen
                            <br />
                            <input type="text" name="nameFile" id="nameFile" class="form-control" />

                        </div>
                    </div>


                </div>
            </div>
            <div class="row">
                <div class="col-md-4">
                </div>
                <div class="form-group">
                    <div class="col-md-2">
                        <a href="/Sponsors/Index" class="btn btn-primary btn-md text-uppercase">Cancelar</a>
                    </div>
                </div>
                <div class="form-group">
                    <div class="col-md-2">
                        <input type="submit" value="Guardar" class="btn btn-primary btn-md text-uppercase" />
                    </div>
                </div>
            </div>
            <br />
        </div>
    </div>
}
<hr />

<style>

    #mainNav {
        background-color: rgb(46,49,146);
    }

    .md-3 {
        box-shadow: 5px 0px 40px rgba(0,0,0, .2);
        width: 97%;
        margin-top: 8%;
    }

    .panel {
        border-radius: 0 !important;
        transition: box-shadow 0.5s;
        width: 55%;
    }

    .form-group {
        align-content: center;
    }
</style>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

ProyectoIngenieria/ProyectoIngenieria/Views/Sponsors/CreateSponsorEnterprise.cshtml
@model ProyectoIngenieria.DB.Sponsor

@{
    ViewBag.Title = "Create";
}
@Html.Partial("~/Views/Home/AdminMenu.cshtml")
@using (Html.BeginForm("CreateSponsorEnterprise", "Sponsors", FormMethod.Post, new { enctype = "multipart/form-data" }))
{
    @Html.AntiForgeryToken()



    <div class="container md-3">
        <br />
        <h1 class="text-center">Ingresar un Patrocinador Empresa</h1>
        <br />

        @if (ViewBag.message != null)
        {
            <div class="alert alert-danger text-center alert-dismissible">
                <h4 class="alert-heading"><i class="icon fa fa-check"></i> ¡Error!</h4>
                <button type="button" class="close" data-dismiss="alert" aria-hidden="true">x</button>
                <h6>@ViewBag.message</h6>
            </div>
        }
        <br />
        <div class="panel-body">
            <div class="row">
                <div class="col-md-1"></div>
                <div class="col-md-5">
                    @Html.ValidationSummary(true, "", new { @class = "text-danger" })
                    <div class="form-group">

                        <div class="col-md-10">
                            <a>Cédula Jurídica</a>
                            @Html.EditorFor(model => model.identification, new { htmlAttributes = new { @class = "form-control" } })
                            @Html.ValidationMessageFor(model => model.identification, "", new { @class = "text-danger" })
                        </div>
                    </div>

                    <div class="form-group">
                        @Html.LabelFor(model => model.name, htmlAttributes: new { @class = "control-label col-md-2" })
                        <div class="col-md-10">
                            @Html.EditorFor(model => model.name, new { htmlAttributes = new { @class = "form-control" } })
                            @Html.ValidationMessageFor(model => model.name, "", new { @class = "text-danger" })
                        </div>
                    </div>

                    <div class="form-group">

                        <div class="col-md-10">
                            <a>Tipo</a>
                            @Html.EditorFor(model => model.last_name, new { htmlAttributes = new { @class = "form-control", @Value = "Empresa", @readonly = "readonly" } })
                        </div>
                    </div>

                    <div class="form-group">
                        @Html.LabelFor(model => model.email, htmlAttributes: new { @class = "control-label col-md-2" })
                        <div class="col-md-10">
                            @Html.EditorFor(model => model.email, new { htmlAttributes = new { @class = "form-control" } })
                            @Html.ValidationMessageFor(model => model.email, "", new { @class = "text-danger" })
                        </div>
                    </div>
                </div>
                <div class="col-md-5">
                    <div class="form-group">
                        @Html.LabelFor(model => model.phone_number, htmlAttributes: new { @class = "control-label col-md-2" })
                        <div class="col-md-10">
                            @Html.EditorFor(model => model.phone_number, new { htmlAttributes = new { @class = "form-control" } })
                            @Html.ValidationMessageFor(model => model.phone_number, "", new { @class = "text-danger" })
                        </div>
                    </div>

                    <div class="form-group">
                        @Html.LabelFor(model => model.description, htmlAttributes: new { @class = "control-label col-md-2" })
                        <div class="col-md-10">
                            @Html.EditorFor(model => model.description, new { htmlAttributes = new { @class = "form-control" } })
                            @Html.ValidationMessageFor(model => model.description, "", new { @class = "text-danger" })
                        </div>
                    </div>

                    <div class="form-group">

                        <div class="col-md-10">
                            Seleccione una foto
                            <br />
                            <input type="file" name="File" id="File" />
                        </div>
                        @if (ViewBag.Photo != null)
                        {
                            <div class="col-md-10">
                                <div class="alert alert-danger">
                                    @ViewBag.Photo
                                </div>
                            </div>
                        }
                    </div>

                    <div class="form-group">

                        <div class="col-md-10">
                            Nombre de la imagen
                            <br />
                            <input type="text" name="nameFile" id="nameFile" class="form-control" />

                        </div>
                        @if (ViewBag.MessagePhotoName != null)
                        {
                            <div class="col-md-10">
                                <div class="alert alert-danger">
                                    @ViewBag.MessagePhotoName
                                </div>
                            </div>
                        }
                    </div>
                </div>
            </div>
            <div class="row">
                <div class="col-md-4">
                </div>
                <div class="form-group">
                    <div class="col-md-2">
                        <a href="/Sponsors/Index" class="btn btn-primary btn-md text-uppercase">Cancelar</a>
                    </div>
                </div>
                <div class="form-group">
                    <div class="col-md-2">
                        <input type="submit" value="Guardar" class="btn btn-primary btn-md text-uppercase" />
                    </div>
                </div>
            </div>
            <br />
        </div>
    </div>
}
<hr />

<style>

    #mainNav {
        background-color: rgb(46,49,146);
    }

    .md-3 {
        box-shadow: 5px 0px 40px rgba(0,0,0, .2);
        width: 97%;
        margin-top: 8%;
    }

    .panel {
        border-radius: 0 !important;
        transition: box-shadow 0.5s;
        width: 55%;
    }

    .form-group {
        align-content: center;
    }
</style>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

ProyectoIngenieria/ProyectoIngenieria/Views/Sponsors/Delete.cshtml
@model ProyectoIngenieria.DB.Sponsor

@{
    ViewBag.Title = "Delete";
}

@Html.Partial("~/Views/Home/AdminMenu.cshtml")

<div class="container md-3">
    <br />
    <h3 class="text-center">¿Está seguro que desea eliminar el patrocinador?</h3>
    <br />
    <br />
    <div class="panel-body ">
        <div class="row">

            <div class="col-sm-6 ">

                <dl class="dl-horizontal margen">
                    <dt>
                        <p class="text-muted">@Html.DisplayNameFor(model => model.name)</p>
                    </dt>

                    <dd>
                        @Html.DisplayFor(model => model.name)
                    </dd>

                    <dt>
                        <p class="text-muted"> @Html.DisplayNameFor(model => model.last_name)</p>
                    </dt>

                    <dd>
                        @Html.DisplayFor(model => model.last_name)
                    </dd>

                    <dt>
                        <p class="text-muted">@Html.DisplayNameFor(model => model.email)</p>
                    </dt>

                    <dd>
                        @Html.DisplayFor(model => model.email)
                    </dd>

                    <dt>
                        <p class="text-muted">@Html.DisplayNameFor(model => model.phone_number)</p>
                    </dt>

                    <dd>
                        @Html.DisplayFor(model => model.phone_number)
                    </dd>

                    <dt>
                        <p class="text-muted">@Html.DisplayNameFor(model => model.description)</p>
                    </dt>

                    <dd>
                        @Html.DisplayFor(model => model.description)
                    </dd>

                </dl>
            </div>
            <div class="col-sm-6">
                <img src="@(ViewBag.image)" width="65%;" height="65%;" class="img rounded-circle" />
            </div>
        </div>
    </div>
    <br />

    <div class="row" style="margin-top:2%;">
        <div class="col-md-4">
        </div>
        <div class="form-group">
            <div class="col-md-2">
                <a href="/Sponsors/Index" class="btn btn-primary btn-md text-uppercase">Cancelar</a>
            </div>
        </div>
        <div class="form-group">
            <div class="col-md-2">
                @using (Html.BeginForm())
                {
                    @Html.AntiForgeryToken()

                    <input type="submit" value="Eliminar" class="btn btn-primary btn-md text-uppercase" />
                }
            </div>
        </div>
    </div>

    <br />
    <br />
</div>
<hr />

<style>
    .img {
        margin-top: -1%;
        margin-left: 15%;
    }

    .margen {
        margin-left: 22%;
    }

    #mainNav {
        background-color: rgb(46,49,146);
    }

    .md-3 {
        box-shadow: 5px 0px 40px rgba(0,0,0, .2);
        width: 60%;
        margin-top: 8%;
    }

    .panel {
        border-radius: 0 !important;
        transition: box-shadow 0.5s;
        width: 55%;
    }
</style>

ProyectoIngenieria/ProyectoIngenieria/Views/Sponsors/Edit.cshtml
@model ProyectoIngenieria.DB.Sponsor

@{
    ViewBag.Title = "Edit";
}
@Html.Partial("~/Views/Home/AdminMenu.cshtml")
@using (Html.BeginForm("Edit", "Sponsors", FormMethod.Post, new { enctype = "multipart/form-data" }))
{
    @Html.AntiForgeryToken()


    @Html.ValidationSummary(true, "", new { @class = "text-danger" })
    @Html.HiddenFor(model => model.identification)
    @Html.HiddenFor(model => model.photo_id)
    <div class="container md-3">
        <br />
        <h1 class="text-center">Actualizar patrocinador</h1>

        <div class="panel-body">
            <div class="row">
                <div class="col-md-1"></div>
                <div class="col-md-5">
                    <div class="form-group">
                        @Html.LabelFor(model => model.name, htmlAttributes: new { @class = "control-label col-md-2" })
                        <div class="col-md-10">
                            @Html.EditorFor(model => model.name, new { htmlAttributes = new { @class = "form-control" } })
                            @Html.ValidationMessageFor(model => model.name, "", new { @class = "text-danger" })
                        </div>
                    </div>

                    <div class="form-group">

                        <div class="col-md-10">
                            @if (ViewBag.enterprise != null)
                            {
                                <a>Tipo</a>
                                @Html.EditorFor(model => model.last_name, new { htmlAttributes = new { @class = "form-control", @Value = ViewBag.enterprise, @readonly = "readonly" } })
                            }
                            else
                            {
                                @Html.LabelFor(model => model.last_name, htmlAttributes: new { @class = "control-label col-md-1" })
                                @Html.EditorFor(model => model.last_name, new { htmlAttributes = new { @class = "form-control" } })
                            }
                            @Html.ValidationMessageFor(model => model.last_name, "", new { @class = "text-danger" })
                        </div>
                    </div>

                    <div class="form-group">
                        @Html.LabelFor(model => model.email, htmlAttributes: new { @class = "control-label col-md-2" })
                        <div class="col-md-10">
                            @Html.EditorFor(model => model.email, new { htmlAttributes = new { @class = "form-control" } })
                            @Html.ValidationMessageFor(model => model.email, "", new { @class = "text-danger" })
                        </div>
                    </div>

                    <div class="form-group">
                        @Html.LabelFor(model => model.phone_number, htmlAttributes: new { @class = "control-label col-md-2" })
                        <div class="col-md-10">
                            @Html.EditorFor(model => model.phone_number, new { htmlAttributes = new { @class = "form-control" } })
                            @Html.ValidationMessageFor(model => model.phone_number, "", new { @class = "text-danger" })
                        </div>
                    </div>

                    <div class="form-group">
                        @Html.LabelFor(model => model.description, htmlAttributes: new { @class = "control-label col-md-2" })
                        <div class="col-md-10">
                            @Html.EditorFor(model => model.description, new { htmlAttributes = new { @class = "form-control" } })
                            @Html.ValidationMessageFor(model => model.description, "", new { @class = "text-danger" })
                        </div>
                    </div>
                </div>
                <div class="col-md-5">
                    <div class="form-group">
                        <a>Foto Actual</a>
                        <div class="col-md-10">

                            <img src="@(ViewBag.image)" width="60%;" height="100%;" />
                        </div>
                    </div>

                    <div class="form-group">

                        <div class="col-md-10">
                            Seleccione una foto
                            <br />
                            <input type="file" name="File" id="File" class="form-group" />
                        </div>
                    </div>

                    <div class="form-group">

                        <div class="col-md-10">
                            Nombre de la imagen
                            <br />
                            <input type="text" name="nameFile" id="nameFile" value="@(ViewBag.name)" class="form-control" />

                        </div>
                    </div>

                </div>
            </div>
            <div class="row">
                <div class="col-md-4">
                </div>
                <div class="col-md-2">
                    <div class="form-group">
                        <a href="~/Sponsors/Index" class="btn btn-primary btn-md text-uppercase">Cancelar</a>
                    </div>
                </div>
                <div class="col-md-2">
                    <div class="form-group">
                        <input type="submit" value="Guardar Cambios" class="btn btn-primary btn-md text-uppercase" />
                    </div>
                </div>
            </div>
        </div>
        <br />
    </div>

}
<hr />

<style>

    #mainNav {
        background-color: rgb(46,49,146);
    }

    .md-3 {
        box-shadow: 5px 0px 40px rgba(0,0,0, .2);
        width: 97%;
        margin-top: 10%;
    }

    .panel {
        border-radius: 0 !important;
        transition: box-shadow 0.5s;
        width: 55%;
    }

    .form-group {
        align-content: center;
    }
</style>



@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}