ProyectoIngenieria/ProyectoIngenieria/Controllers/PhotosController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.IO;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using ProyectoIngenieria.DB;

namespace ProyectoIngenieria.Controllers
{
    public class PhotosController : Controller
    {
        private ProyectoIngenieriaEntities db = new ProyectoIngenieriaEntities();

        // GET: Photos
        public ActionResult Index()
        {
            return View(db.Photo.ToList());
        }

        // GET: Photos/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Photo photo = db.Photo.Find(id);
            if (photo == null)
            {
                return HttpNotFound();
            }
            return View(photo);
        }

        // GET: Photos/Create
        public ActionResult Create()
        {

            List<Album> albums = db.Album.ToList();
            ViewBag.albums = albums;
            return View();
        }

        // POST: Photos/Create
        // Para protegerse de ataques de publicación excesiva, habilite las propiedades específicas a las que desea enlazarse. Para obtener 
        // más información vea https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "id,name,image")] Photo photo, List<int> albums, HttpPostedFileBase File)
        {
            List<Album> albumes = db.Album.ToList();
            if (ModelState.IsValid)
            {
                if (albums != null)
                {
                    if (albums.Count > 0)
                    {
                        System.Collections.IList listAlbums = albums;
                        for (int i = 0; i < listAlbums.Count; i++)
                        {
                            string id = "" + listAlbums[i];
                            Album album = db.Album.Find(id);
                            photo.Album.Add(album);

                        }
                    }
                }

                if (File == null)
                {
                    ViewBag.MessagePhoto = "Debe ingresar una imagen";
                    ViewBag.MessageList = "Debe seleccionar datos";
                    return View();
                }
                else
                {
                    var extension = Path.GetExtension(File.FileName);
                    var path = Path.Combine(Server.MapPath("/Static/"), photo.name + extension);


                    photo.name = photo.name;
                    photo.image = photo.name + extension;
                    File.SaveAs(path);
                }
                
                db.Photo.Add(photo);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            ViewBag.album = new SelectList(db.Album, "identification", "name", photo.Album);


            return View(photo);
        }

        // GET: Photos/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Photo photo = db.Photo.Find(id);
            if (photo == null)
            {
                return HttpNotFound();
            }
            ViewBag.image = Path.Combine("/Static/", photo.image);
            ViewBag.name = photo.name;
            return View(photo);
        }

        // POST: Photos/Edit/5
        // Para protegerse de ataques de publicación excesiva, habilite las propiedades específicas a las que desea enlazarse. Para obtener 
        // más información vea https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "id,name,image")] Photo photo, HttpPostedFileBase File, string nameFile)
        {
            if (ModelState.IsValid)
            {

                var image = db.Photo.Find(photo.id);
               
                if (File != null)
                {
                    Photo imag = db.Photo.Find(photo.id);
                    imag.name = nameFile;

                    
                    var locationStatic = Path.Combine(Server.MapPath("/Static/"));
                    System.IO.File.Delete(locationStatic + imag.image);

                    
                    var fileName = Path.GetExtension(File.FileName);
                    imag.image = nameFile + fileName;
                    var path = Path.Combine(Server.MapPath("/Static/"), nameFile + fileName);

                    File.SaveAs(path);

                    db.SaveChanges();
                }
                if (nameFile != image.name)
                {
                    var Photo = db.Photo.Find(photo.id);
                    Photo.name = nameFile;

                    db.SaveChanges();
                }

                db.SaveChanges();
               db.Entry(photo).State = EntityState.Modified;
                return RedirectToAction("Index");
            }
            return View(photo);
        }

        // GET: Photos/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Photo photo = db.Photo.Find(id);
            if (photo == null)
            {
                return HttpNotFound();
            }
            return View(photo);
        }

        // POST: Photos/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Photo photo = db.Photo.Find(id);
            db.Photo.Remove(photo);
            
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

ProyectoIngenieria/ProyectoIngenieria/Views/Photos/Create.cshtml
@model ProyectoIngenieria.DB.Photo

@{
    ViewBag.Title = "Create";
}

@Html.Partial("~/Views/Home/AdminMenu.cshtml")



@using (Html.BeginForm("Create", "Photos", FormMethod.Post, new { enctype = "multipart/form-data" }))
{
    @Html.AntiForgeryToken()

    <div class="container md-3">
        <br />
        <h1 class="text-center">Ingresar una Foto</h1>
        <br />
        <br />
        <div class="panel-body">
            <div class="row">
                <div class="col-md-3"></div>
                <div class="col-md-8">
                    @Html.ValidationSummary(true, "", new { @class = "text-danger" })
                    <div class="form-group">
                        @Html.LabelFor(model => model.name, htmlAttributes: new { @class = "control-label col-md-2" })
                        <div class="col-md-10">
                            @Html.EditorFor(model => model.name, new { htmlAttributes = new { @class = "form-control" } })
                            @Html.ValidationMessageFor(model => model.name, "", new { @class = "text-danger" })
                        </div>
                    </div>
                    <div class="form-group">

                        <div class="col-md-10">
                            Seleccione una foto
                            <br />
                            <input type="file" name="File" id="File" />
                        </div>
                        @if (ViewBag.MessagePhoto != null)
                        {
                            <div class="col-md-10">
                                <div class="alert alert-danger">
                                    @ViewBag.MessagePhoto
                                </div>
                            </div>
                        }
                    </div>

                    @Html.LabelFor(model => model.Album, htmlAttributes: new { @class = "control-label col-md-2" })
                    <div class="col-md-10">
                        <select multiple="multiple" style="width:100%" ; id="sponsors" name="sponsors">
                            @foreach (var item in ViewBag.albums)
                            {
                                <option value="@item.id">@item.name </option>
                            }
                            <option value="0">Ninguno</option>
                        </select>

                    </div>


                    <div class="row">
                        <div class="col-md-2">
                        </div>
                        <div class="form-group">
                            <div class="col-md-2">
                                <a href="~/Photos/Index" class="btn btn-primary btn-md text-uppercase">Cancelar</a>
                            </div>
                        </div>
                        <div class="form-group">
                            <div class="col-md-2">
                                <input type="submit" value="Guardar" class="btn btn-primary btn-md text-uppercase" />
                            </div>
                        </div>
                    </div>
                </div>
            </div>
            <br />
        </div>
    </div>
}

<style>

    #mainNav {
        background-color: rgb(46,49,146);
    }

    .md-3 {
        box-shadow: 5px 0px 40px rgba(0,0,0, .2);
        width: 97%;
        margin-top: 10%;
    }

    .panel {
        border-radius: 0 !important;
        transition: box-shadow 0.5s;
        width: 55%;
    }

    .form-group {
        align-content: center;
    }
</style>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

ProyectoIngenieria/ProyectoIngenieria/Views/Photos/Delete.cshtml
@model ProyectoIngenieria.DB.Photo

@{
    ViewBag.Title = "Delete";
}

<h2>Delete</h2>

<div class="container md-3">
    <br />
    <h1 class="text-center">Detalles del Responsable</h1>
    <br />
    <br />
    <div class="panel-body">
        <div class="row">
            <div class="col-md-3"></div>
            <div class="col-md-8">
                <div class="row" style="text-align: center;">
                    <div class="col-sm-2">
                        @Html.DisplayNameFor(model => model.name)
                        <br />
                        @Html.DisplayFor(model => model.name)
                    </div>

                    <div class="col-sm-2">
                        @Html.DisplayNameFor(model => model.image)
                        <br />
                        @Html.DisplayFor(model => model.image)
                    </div>

                    <div class="row" style="margin-top:2%;">
                        <div class="col-md-10">
                        </div>

                        <br />
                        <br />
                        <div class="form-group">

                            <div class="col-md-2">
                                <a href="/Photos/Index" class="btn btn-primary btn-md text-uppercase">Cancelar</a>
                            </div>
                        </div>
                        <div class="form-group">
                            <div class="col-md-2">
                                @using (Html.BeginForm())
                                {
                                    @Html.AntiForgeryToken()

                                    <input type="submit" value="Eliminar" class="btn btn-primary btn-md text-uppercase" />
                                }
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

            <style>

                #mainNav {
                    background-color: rgb(46,49,146);
                }

                .md-3 {
                    box-shadow: 5px 0px 40px rgba(0,0,0, .2);
                    width: 97%;
                    margin-top: 10%;
                }

                .panel {
                    border-radius: 0 !important;
                    transition: box-shadow 0.5s;
                    width: 55%;
                }

                .form-group {
                    align-content: center;
                }
            </style>

ProyectoIngenieria/ProyectoIngenieria/Views/Photos/Details.cshtml
@model ProyectoIngenieria.DB.Photo

@{
    ViewBag.Title = "Details";
}

<h2>Details</h2>

<div>
    <h4>Photo</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.name)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.name)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.image)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.image)
        </dd>

    </dl>
</div>
<p>
    @Html.ActionLink("Edit", "Edit", new { id = Model.id }) |
    @Html.ActionLink("Back to List", "Index")
</p>

ProyectoIngenieria/ProyectoIngenieria/Views/Photos/Edit.cshtml
@model ProyectoIngenieria.DB.Photo

@{
                /**/

                ViewBag.Title = "Edit";
}

<h2>Edit</h2>


@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()


    <div class="form-horizontal">
        <h4>Fotos</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.id)
        <div class="container md-3">
            <br />
            <h1 class="text-center">Actualizar un Album</h1>
            <br />
            <br />
            <div class="panel-body">
                <div class="row">
                    <div class="col-md-3"></div>
                    <div class="col-md-8">
                        <div class="form-group">
                            @Html.LabelFor(model => model.name, htmlAttributes: new { @class = "control-label col-md-2" })
                            <div class="col-md-10">
                                @Html.EditorFor(model => model.name, new { htmlAttributes = new { @class = "form-control" } })
                                @Html.ValidationMessageFor(model => model.name, "", new { @class = "text-danger" })
                            </div>
                        </div>

                        <div class="form-group">
                            @Html.LabelFor(model => model.id, htmlAttributes: new { @class = "control-label col-md-2" })
                            <div class="col-md-10">
                                @Html.EditorFor(model => model.id, new { htmlAttributes = new { @class = "form-control", @readonly = "readonly", @placeholder = "prueba" } })
                            </div>
                        </div>
                    </div>
                    <div class="col-md-5">
                        <div class="form-group">

                            <div class="form-group">
                                <a>Foto Actual</a>
                                <div class="col-md-10">
                                    <img src="@(ViewBag.image)" width="50%;" height="100%;" />
                                </div>
                            </div>
                            <div class="col-md-10">
                                <a>Seleccione una nueva foto</a>
                                <br />
                                <input type="file" name="File" id="File" />
                            </div>
                        </div>
                        <br />
                        <div class="form-group">

                            <div class="col-md-10">
                                <a>Nombre de la imagen</a>
                                <br />
                                <input type="text" name="nameFile" id="nameFile" value="@(ViewBag.name)" />
                            </div>
                        </div>
                        <br />
                    </div>
                </div>

                <div class="row">
                    <div class="col-md-2">
                    </div>
                    <div class="col-md-2">
                        <div class="form-group">
                            <a href="~/Photos/Index" class="btn btn-primary btn-md text-uppercase">Cancelar</a>
                        </div>
                    </div>
                    <div class="col-md-1">
                    </div>
                    <div class="col-md-2">
                        <div class="form-group">
                            <input type="submit" value="Guardar Cambios" class="btn btn-primary btn-md text-uppercase" />
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <br />
   
}
<hr />

<style>

    #mainNav {
        background-color: rgb(46,49,146);
    }

    .md-3 {
        box-shadow: 5px 0px 40px rgba(0,0,0, .2);
        width: 97%;
        margin-top: 10%;
    }

    .panel {
        border-radius: 0 !important;
        transition: box-shadow 0.5s;
        width: 55%;
    }

    .form-group {
        align-content: center;
    }
</style>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

ProyectoIngenieria/ProyectoIngenieria/Views/Photos/Index.cshtml
@model IEnumerable<ProyectoIngenieria.DB.Photo>

@{
    ViewBag.Title = "Index";
}

@Html.Partial("~/Views/Home/AdminMenu.cshtml")

<div class="container md-3">
    <br />
    <h1 class="text-center">Fotos</h1>
    <br />
    <br />
    <div class="row">
        <div class="col-sm-9"></div>
        <div class="col-sm-3 ">
            <a href="~/Photos/Create" class="btn btn-primary btn-md text-uppercase">Añadir Nuevo</a>
        </div>
    </div>
    <div class="panel-body">
        <br />
        <table class="table ">
            <tr class="text-center">
                <th>
                    Nombre
                </th>

                <th></th>
            </tr>

            @foreach (var item in Model)
            {
                <tr class="text-center">

                    <td>
                        @Html.DisplayFor(modelItem => item.name)
                    </td>

                    <td>
                        @Html.ActionLink("Editar", "Edit", new { id = item.id }) |

                        @Html.ActionLink("Eliminar", "Delete", new { id = item.id })|
                        @Html.ActionLink("Detalles", "Details", new { id = item.id })

                    </td>
                </tr>
            }

        </table>
        <br />
        <div class="row">
            <div class="col-sm-5"></div>
            <div class="col-sm-6 ">

            </div>
        </div>
        <div class="col-sm-3 ">
            <a href="~/Home/AdminView" class="btn btn-primary btn-md text-uppercase">Regresar</a>
        </div>

    </div>
    <br />
    <br />
</div>
<hr />

<style>

    #mainNav {
        background-color: rgb(46,49,146);
    }

    .md-3 {
        box-shadow: 5px 0px 40px rgba(0,0,0, .2);
        width: 97%;
        margin-top: 10%;
    }

    .panel {
        border-radius: 0 !important;
        transition: box-shadow 0.5s;
        width: 55%;
    }
</style>